### ISSUE TITLE
Tests for environment token

### ISSUE THREAD

**Issue by mcg1969** [Anaconda-Platform/anaconda-anon-usage#11]
Right now all of our tests sit in the base environment. We need tests to make sure the environment token retrieval is working.

**Comment by jezdez** [comment]
I added a unit test in [`6a0532b` (#15)](https://github.com/Anaconda-Platform/anaconda-anon-usage/pull/15/commits/6a0532b0ef92febad0e5d6094084e641a93e8234), does this suffice?

**Comment by mcg1969** [comment]
Not quite. That's a good test but we need an integration test on a child environment, much like what python/test_config.py does

**Comment by jezdez** [comment]
Gotcha, thank you! Given the timeline, I'll move this to the next milestone, we have some good changes for the next 0.4.0 IMO.
