### ISSUE TITLE
issue with interrupted environment creation

### ISSUE THREAD

**Issue by mcg1969** [Anaconda-Platform/anaconda-anon-usage#21]
```
conda create -n testchild1 --yes -c https://repo.anaconda.com/pkgs/fakechannel fakepackage
conda install -n testchild1 xz
```
The second command produces this error:
```
DirectoryNotACondaEnvironmentError: The target directory exists, but it is not a conda environment.
Use 'conda create' to convert the directory to a conda environment.
  target directory: /Users/mgrant/testenv/envs/testchild1
```
This happens because the first command successfully creates the token, but conda now recognizes the directory as a non-empty directory that is not a conda environment, so it cannot proceed with the second.

The solution involves, at least in part, not creating an environment token until after the directory has been created. Ideally, the token is saved at a later point in the process.

**Comment by jezdez** [comment]
Closed via #22.
